name: Python Postgres Test

on:
  push:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest

    # Service container: Postgres
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Check out repository code
        uses: actions/checkout@v5

      # Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests psycopg2 python-dotenv

      # Run pytest
      - name: Run tests
        run: python -m pytest tests/ -v
        env:
          DB_HOST: localhost
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASS: testpass